### ISSUE TITLE
Null value set for empty last name 

### ISSUE THREAD

**Issue by suryan-s** [pieroguerrero/cv-creator#1]
![Screenshot_20221207_083546](https://user-images.githubusercontent.com/76394506/206078259-9a534633-3fff-4099-84e8-2622e4f62667.png)

While filling the name , when unrequired field are left blank, default null is assigned

**Comment by pieroguerrero** [comment]
Thank you for the input @suryan-s . 
I will try to book some time to fix it. However, if you want to contribute to fix it, you are more than welcome!!

**Comment by suryan-s** [comment]
hey @pieroguerrero 
thank you for the quick response. Man, i wish i could help but I'm just user in this case.

**Comment by pieroguerrero** [comment]
> hey @pieroguerrero thank you for the quick response. Man, i wish i could help but I'm just user in this case.

Don't worry, I will fix it by 12/23/22 max.
